name: ustay_project
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:


  flutter:
    sdk: flutter
  #Pensando en cambiar
  http: ^1.2.2
  #Nueva Conexion
  dio: ^5.3.2
  xml: ^6.1.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  leak_tracker: ^10.0.5
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.0.0
  cached_network_image: ^3.2.3


  google_fonts:
  cupertino_icons: ^1.0.8

dev_dependencies:
  fake_async: ^1.3.1
  leak_tracker_flutter_testing: ^3.0.5
  lints: ^5.0.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    #Images
    - assets/images/common/

    #ImagesCards
    - assets/images/common/cards/

    #Icons
    - assets/icons/icon-buy.png
    - assets/icons/icon-favorite.png
    - assets/icons/icon-filter.png
    - assets/icons/icon-grid.png
    - assets/icons/icon-home.png
    - assets/icons/icon-navigator.png
    - assets/icons/icon-next.png
    - assets/icons/icon-notification.png
    - assets/icons/icon-person.png
    - assets/icons/icon-search.png
    - assets/icons/icon-session.png
    - assets/icons/icon-password.png
    - assets/icons/icon-email.png


  uses-material-design: true
